# version: '3.1'

# services:

#   wordpress:
#     image: wordpress
#     restart: always
#     ports:
#       - 8080:80
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: exampleuser
#       WORDPRESS_DB_PASSWORD: examplepass
#       WORDPRESS_DB_NAME: exampledb
#     volumes:
#       - ./wordpress:/var/www/html

#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_DATABASE: exampledb
#       MYSQL_USER: exampleuser
#       MYSQL_PASSWORD: examplepass
#       MYSQL_RANDOM_ROOT_PASSWORD: '1'
#     volumes:
#       - ./db:/var/lib/mysql

# volumes:
#   wordpress:
#   db:
version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306  # Poort toegevoegd
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
      - ./schema/:/docker-entrypoint-initdb.d


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpassword  # Gebruik een vaste root-wachtwoord
    volumes:
      - ./db:/var/lib/mysql  # Controleer dat dit pad klopt
